### ISSUE TITLE
Te lucis p. 47

### ISSUE THREAD

**Issue by jdbrosses** [xmarteo/Carnet_RG_2023#2]
Je ne sais pas si c'est pertinent, mais l'appli Completorium me donne un autre ton pour le Te lucis, spécifique à la fête du Christ-Roi : Te(d) lu(d)cis(f) an(d)te(c) ter(f)mi(g)num(h) ...

**Comment by xmarteo** [comment]
C'est vrai, mais on va célébrer un dimanche ordinaire dans le reste de la liturgie, et les gens pourront plus facilement réutiliser l'air "in dominicis et festis minoribus" qui est le plus connu. Mais bonne suggestion :)
